### PR TITLE
adds fhir-schema to sdk

### PR DESCRIPTION
**Pull request by Glumli**

### CODE REVIEW

**Comment by Harsimran1** [comment]
Why ? This will drastically increase the size of SDK.  Is it temporary?  I suggest we host the schema somewhere and not add in SDK.

**Comment by Glumli** [comment]
@Harsimran1  https://gesundheitscloud.atlassian.net/browse/HC-1510
Tobi asked for it.. I guess at least for the demo this is ok.

**Comment by theintz** [comment]
Does this add the *entire* FHIR schema? Or just the bits that we need?

**Comment by Harsimran1** [comment]
It adds the entire FHIR schema. but when loaded over API , it reduces down to 30KB (on first request, and later loaded from disc cache).

**Pull request merged**
